In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df=pd.read_csv("/content/london_houses.csv")
print(len(df))

1000

In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df=pd.read_csv("/content/london_houses.csv")
ma=df['Price (£)'].mean()
ma

np.float64(1840807.278)

In [4]:

import pandas as pd
from sklearn.linear_model import LinearRegression

df=pd.read_csv("/content/london_houses.csv")
df

                   Address  Neighborhood  ...  Building Status  Price (£)
0         78 Regent Street  Notting Hill  ...        Renovated    2291200
1        198 Oxford Street   Westminster  ...              Old    1476000
2         18 Regent Street          Soho  ...        Renovated    1881600
3     39 Piccadilly Circus     Islington  ...        Renovated    1896000
4         116 Fleet Street    Marylebone  ...              Old    1524000
..                     ...           ...  ...              ...        ...
995  44 Camden High Street   Westminster  ...        Renovated    1166400
996          165 Park Lane        Camden  ...              Old     563333
997  99 Camden High Street        Camden  ...              Old    1986399
998          155 Park Lane        Camden  ...        Renovated    1703000
999       145 Baker Street    Kensington  ...              Old    2343333

[1000 rows x 17 columns]

In [11]:
df['Property Type'].mode()[0]

'Detached House'

In [12]:
df['Property Type'].value_counts()

Property Type
Detached House    349
Semi-Detached     345
Apartment         306
Name: count, dtype: int64

In [13]:
df.isna().sum()

Address            0
Neighborhood       0
Bedrooms           0
Bathrooms          0
Square Meters      0
Building Age       0
Garden             0
Garage             0
Floors             0
Property Type      0
Heating Type       0
Balcony            0
Interior Style     0
View               0
Materials          0
Building Status    0
Price (£)          0
dtype: int64

In [20]:
from types import new_class
import pandas as pd
from sklearn.linear_model import LinearRegression

df=pd.read_csv("/content/london_houses.csv")
x=df[['Square Meters','Bedrooms','Building Age']]
y=df['Price (£)']

cv=LinearRegression()
cv.fit(x,y)
print("Size weight(a):",cv.coef_[0])
print("Bedroom weight(b):",cv.coef_[1])
print("Age weight(d):",cv.coef_[2])
print("constant(C):",cv.intercept_)

size=int(input("Enter the size of the house:"))
bedroom=int(input("Enter the number of bedrooms:"))
age=int(input("Enter the age of the house:"))

new_data=pd.DataFrame([[size,bedroom,age]],columns=['Square Meters','Bedrooms','Building Age'])
predicted_price=cv.predict(new_data)
print("Predicted house price:",predicted_price)

Size weight(a): 11972.488747561812
Bedroom weight(b): 186.1872669486288
Age weight(d): 749.1962379807494
constant(C): 11405.131902544294
Enter the size of the house:2
Enter the number of bedrooms:2
Enter the age of the house:2
Predicted house price: [37220.87640753]